/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

/**
 *
 * @author ASUS
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCatalogo = new javax.swing.JMenu();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemProductos = new javax.swing.JMenuItem();
        jMenuItemCategorias = new javax.swing.JMenuItem();
        jMenuItemIncidente = new javax.swing.JMenuItem();
        jMenuItemCategoriaIncident = new javax.swing.JMenuItem();
        jMenuOperaciones = new javax.swing.JMenu();
        jMenuItemLista = new javax.swing.JMenuItem();
        jMenuItemEliminar = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItemBuscar = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemIndicente = new javax.swing.JMenuItem();
        jMenuItemVentas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuCatalogo.setText("catalogo");
        jMenuCatalogo.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuCatalogoMenuSelected(evt);
            }
        });
        jMenuCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCatalogoActionPerformed(evt);
            }
        });

        jMenuItemClientes.setText("Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuCatalogo.add(jMenuItemClientes);

        jMenuItemProductos.setText("Productos");
        jMenuItemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductosActionPerformed(evt);
            }
        });
        jMenuCatalogo.add(jMenuItemProductos);

        jMenuItemCategorias.setText("Categorias");
        jMenuItemCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoriasActionPerformed(evt);
            }
        });
        jMenuCatalogo.add(jMenuItemCategorias);

        jMenuItemIncidente.setText("Incidentes");
        jMenuItemIncidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIncidenteActionPerformed(evt);
            }
        });
        jMenuCatalogo.add(jMenuItemIncidente);

        jMenuItemCategoriaIncident.setText("Categoria Incidentes");
        jMenuItemCategoriaIncident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoriaIncidentActionPerformed(evt);
            }
        });
        jMenuCatalogo.add(jMenuItemCategoriaIncident);

        jMenuBar1.add(jMenuCatalogo);

        jMenuOperaciones.setText("operaciones");
        jMenuOperaciones.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuOperacionesMenuSelected(evt);
            }
        });

        jMenuItemLista.setText("Lista");
        jMenuOperaciones.add(jMenuItemLista);

        jMenuItemEliminar.setText("Editar");
        jMenuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarActionPerformed(evt);
            }
        });
        jMenuOperaciones.add(jMenuItemEliminar);

        jMenuItem3.setText("Eliminar");
        jMenuOperaciones.add(jMenuItem3);

        jMenuItemBuscar.setText("Buscar");
        jMenuOperaciones.add(jMenuItemBuscar);

        jMenuBar1.add(jMenuOperaciones);

        jMenuConsultas.setText("consultas");

        jMenuItem1.setText("ClientesActivos");
        jMenuConsultas.add(jMenuItem1);

        jMenuItemIndicente.setText("Incidentes");
        jMenuItemIndicente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIndicenteActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemIndicente);

        jMenuItemVentas.setText("Ventas");
        jMenuItemVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVentasActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemVentas);

        jMenuBar1.add(jMenuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCatalogoActionPerformed
        
    }//GEN-LAST:event_jMenuCatalogoActionPerformed

    private void jMenuCatalogoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuCatalogoMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCatalogoMenuSelected

    private void jMenuOperacionesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuOperacionesMenuSelected
        
    }//GEN-LAST:event_jMenuOperacionesMenuSelected

    private void jMenuItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductosActionPerformed
        Productos p=new Productos ();
         p.setLocationRelativeTo(null);
         p.setVisible(true);
    }//GEN-LAST:event_jMenuItemProductosActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        ABCclientes c=new ABCclientes ();
         c.setLocationRelativeTo(null);
         c.setVisible(true);
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarActionPerformed

    }//GEN-LAST:event_jMenuItemEliminarActionPerformed

    private void jMenuItemIndicenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIndicenteActionPerformed
        Incidentes i=new Incidentes ();
         i.setLocationRelativeTo(null);
         i.setVisible(true);
    }//GEN-LAST:event_jMenuItemIndicenteActionPerformed

    private void jMenuItemVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVentasActionPerformed
        Ventas v=new Ventas ();
         v.setLocationRelativeTo(null);
         v.setVisible(true);
    }//GEN-LAST:event_jMenuItemVentasActionPerformed

    private void jMenuItemCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoriasActionPerformed
         Categorias c=new Categorias ();
         c.setLocationRelativeTo(null);
         c.setVisible(true);
    }//GEN-LAST:event_jMenuItemCategoriasActionPerformed

    private void jMenuItemIncidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIncidenteActionPerformed
        Incidentes I=new Incidentes ();
         I.setLocationRelativeTo(null);
         I.setVisible(true);
    }//GEN-LAST:event_jMenuItemIncidenteActionPerformed

    private void jMenuItemCategoriaIncidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoriaIncidentActionPerformed
        CategoriasIncidentes C=new CategoriasIncidentes ();
         C.setLocationRelativeTo(null);
         C.setVisible(true);
    }//GEN-LAST:event_jMenuItemCategoriaIncidentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
 MenuPrincipal mp = new MenuPrincipal ();
    mp.setExtendedState(MAXIMIZED_BOTH);
    mp.setVisible(true);
   
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCatalogo;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemBuscar;
    private javax.swing.JMenuItem jMenuItemCategoriaIncident;
    private javax.swing.JMenuItem jMenuItemCategorias;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemEliminar;
    private javax.swing.JMenuItem jMenuItemIncidente;
    private javax.swing.JMenuItem jMenuItemIndicente;
    private javax.swing.JMenuItem jMenuItemLista;
    private javax.swing.JMenuItem jMenuItemProductos;
    private javax.swing.JMenuItem jMenuItemVentas;
    private javax.swing.JMenu jMenuOperaciones;
    // End of variables declaration//GEN-END:variables
}
